name: "CarConnectivity Addon"
version: "1.0.0"
slug: "carconnectivity-addon"
description: "Addon version of Carconnectivity made by Till (see https://github.com/tillsteinbach/CarConnectivity) throught MQTT"
panel_icon: "mdi:car-wireless"
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
ingress: false
init: false
options:
  connector_type: "seatcupra"
  connector_username: "mail@mail.com"
  connector_password: "password1"
  connector_interval: "600"
  connector_spin: "1234"
  mqtt_username: "mqtt"
  mqtt_password: "password1"
  mqtt_broker: "192.168.1.52"
  log_level: list(info|warning|error|debug)
schema:
  connector_type: list(seatcupra|skoda|volkswagen|tronity)
  connector_username: str
  connector_password: str
  connector_interval: int(60,3600)
  connector_spin: str
  mqtt_username: str
  mqtt_password: str
  mqtt_broker: str
  log_level: list(info|warning|error|debug)